http {
    # 設定日誌格式

    map $http_user_agent $no_logging {
        "~*no-logging" 0;
        default 1;
    }

    # 設定日誌位置
    access_log /home/judge/webserver/log/access.log combined if=$no_logging;

    # 定義伺服器背後的伺服器組 upstream指上游，預設使用Round Robin
    upstream backend_servers { 
        server 192.168.105.1:8080;
        server 192.168.105.2:8080;
    }

    server {
        listen 80;
        server_name nasa.105.cs.nycu file.105.cs.nycu adminer.105.cs.nycu;
        server_tokens off;

        # Redirect all HTTP requests to HTTPS
        location / {
            return 301 https://$host$request_uri; # host: 目標主機名稱 ex: example.com, request_url: 路徑 ex: /path?key=1
        }
    }

    server { # 443 用來監聽ssl(https)
        listen 443 ssl;
        server_name nasa.105.cs.nycu;
        server_tokens off;

        ssl_certificate /home/judge/wildcard.crt;
        ssl_certificate_key /home/judge/wildcard.key;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # 其他 HTTPS 配置...
        location / {
            auth_basic "Auth Basic";
            auth_basic_user_file /usr/local/etc/nginx/.htpasswd;
            root /home/judge/hw4;
            index index.html;

        }

    }

    server { # 443 用來監聽ssl(https)
        listen 443 ssl;
        server_name file.105.cs.nycu;
        server_tokens off;

        ssl_certificate /home/judge/wildcard.crt;
        ssl_certificate_key /home/judge/wildcard.key;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # 其他 HTTPS 配置...
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server { # 443 用來監聽ssl(https)
        listen 443 ssl;
        server_name adminer.105.cs.nycu;
        server_tokens off;

        ssl_certificate /home/judge/wildcard.crt;
        ssl_certificate_key /home/judge/wildcard.key;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # 其他 HTTPS 配置...
        location / {
            root /usr/local/www/nginx/;
            index adminer.php;
        }
    }


    server {
        listen       80;
        server_name  *.105.cs.nycu;
        server_tokens off;

        location / {
            return 301 https://http.cat/404;
        }
    }

}

